## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Type your solution here

# Q1-1
d_frame = pd.DataFrame(data)

# Q1-2
options = ["teacher", "psychologist"]
d_frame_alt1 = d_frame[d_frame["job"].isin(options)]
d_frame_alt2 = d_frame_alt1[d_frame_alt1["num_cars"] > d_frame_alt1["family_size"]]
print(d_frame_alt2)
print("\n")

# Q1-3
d_frame_alt3 = d_frame[d_frame["family_size"] <= 2]
d_frame_alt4 = d_frame_alt3[d_frame_alt3["num_cars"] >= 1]
print(d_frame_alt4)
print("\n")

# Q1-4
unique_list = []
for x in data["job"]:
  if x not in unique_list:
    unique_list.append(x)
len_list = len(unique_list)
print("There are " + str(len_list) + " unique jobs in the dataset.")


   name           job  family_size  num_cars
5  Lisa  psychologist            3         4


    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1


There are 4 unique jobs in the dataset.


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
new_ser = pd.concat([fruit, weights], axis=1)
new_ser.columns = ["fruit", "weight"]
print(new_ser)

bananas = 0
apples = 0
carrots = 0

for j in fruit:
  if j == "apple":
    apples += 1
  elif j == "banana":
    bananas += 1
  elif j == "carrot":
    carrots += 1

_index = new_ser.index
a_con = new_ser["fruit"] == "apple"
b_con = new_ser["fruit"] == "banana"
c_con = new_ser["fruit"] == "carrot"
a_ind = _index[a_con]
b_ind = _index[b_con]
c_ind = _index[c_con]
a_ind_list = a_ind.tolist()
b_ind_list = b_ind.tolist()
c_ind_list = c_ind.tolist()

apple_mean = (sum(a_ind_list)+apples) / apples
banana_mean = (sum(b_ind_list)+bananas) / bananas
carrot_mean = (sum(c_ind_list)+carrots) / carrots

print("The mean weight of apples is", str(apple_mean))
print("The mean weight of bananas is", str(banana_mean))
print("The mean weight of carrots is", str(carrot_mean))



    fruit  weight
0  carrot     1.0
1  carrot     2.0
2  carrot     3.0
3   apple     4.0
4   apple     5.0
5   apple     6.0
6   apple     7.0
7  carrot     8.0
8   apple     9.0
9  banana    10.0
The mean weight of apples is 6.2
The mean weight of bananas is 10.0
The mean weight of carrots is 3.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here

# Q3-1
arr_sorted = np.argsort(course_name)
print(arr_sorted)
print("\n")

# Q3-2
p_start = np.char.startswith(course_name,"P")
p_dframe = pd.DataFrame(p_start, columns=["Starts with \"P\"?"])
print(p_dframe)

[1 3 0 2 4]


   Starts with "P"?
0              True
1             False
2             False
3              True
4             False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here

# Q4-1
array_flip = np.flip(student_id)
print("Student_ID:")
print(student_id)
print("Student_ID Reversed:")
print(array_flip)
print("\n")

# Q4-2
sorted_ind = np.argsort(student_id)
sorted_arr = student_id[sorted_ind]
p = 3
_values = sorted_arr[-p:]
print("3 largest values of Student_ID:")
print(_values)


Student_ID:
[1023 5202 6230 1671 1682 5241 4532]
Student_ID Reversed:
[4532 5241 1682 1671 6230 5202 1023]


3 largest values of Student_ID:
[5202 5241 6230]


**Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
num_arr3 = np.arange(3,100,3)
num_arr5 = np.arange(5,100,5)
con_np = np.concatenate((num_arr3,num_arr5))
con_np_uni = np.unique(con_np)
sum_np = np.sum(con_np_uni)
print("The sum of all multiples of 3 or 5 below 100 equals", str(sum_np))


The sum of all multiples of 3 or 5 below 100 equals 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here

# Q6-1
# I put the creation of the array in this part of the code 
# so columns 1 and 2 don't continue to swap every time the code runs
print("Original array:")
arr = np.arange(12).reshape(3,4)
print(arr)

arr_col = arr
arr_col[:, [1,2]] = arr[:, [2,1]]
print("Column 1 and Column 2 swapped:")
print(arr_col)

# Q6-2
arr_row = arr
arr_row[[0,1]] = arr[[1,0]]
print("Row 0 and Row 1 swapped:")
print(arr_row)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Column 1 and Column 2 swapped:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Row 0 and Row 1 swapped:
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
